<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
    <ApplicationIcon>Images\appIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\appIcon.png" />
    <None Remove="Images\appIcon16.png" />
    <None Remove="Images\CheckboxIcon_Black_Empty.png" />
    <None Remove="Images\CheckboxIcon_White_Empty.png" />
    <None Remove="Images\checkIcon.png" />
    <None Remove="Images\compareOffIcon.png" />
    <None Remove="Images\compareOnIcon.png" />
    <None Remove="Images\crossIcon_White.png" />
    <None Remove="Images\downloadIcon_Black.png" />
    <None Remove="Images\downloadIcon_BorderBlack.png" />
    <None Remove="Images\downloadIcon_Grey.png" />
    <None Remove="Images\downloadIcon_Orange.png" />
    <None Remove="Images\downloadIcon_White.png" />
    <None Remove="Images\errorIcon.png" />
    <None Remove="Images\eyeIcon.png" />
    <None Remove="Images\eyeIcon_Blue.png" />
    <None Remove="Images\folderIcon.png" />
    <None Remove="Images\inferiorLevelIcon.png" />
    <None Remove="Images\infoIcon.png" />
    <None Remove="Images\maximizeIcon.png" />
    <None Remove="Images\minimizeIcon.png" />
    <None Remove="Images\moreDetailsIcon_Closed.png" />
    <None Remove="Images\moreDetailsIcon_Oppened.png" />
    <None Remove="Images\plusIcon_Black.png" />
    <None Remove="Images\plusIcon_White.png" />
    <None Remove="Images\questionIcon_Black.png" />
    <None Remove="Images\startIcon_Black.png" />
    <None Remove="Images\startIcon_Blue.png" />
    <None Remove="Images\startIcon_White.png" />
    <None Remove="Images\stopIcon.png" />
    <None Remove="Images\successIcon.png" />
    <None Remove="Images\warningIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\appIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\appIcon.png" />
    <Resource Include="Images\appIcon16.png" />
    <Resource Include="Images\CheckboxIcon_Black_Empty.png" />
    <Resource Include="Images\CheckboxIcon_White_Empty.png" />
    <Resource Include="Images\crossIcon_White.png" />
    <Resource Include="Images\downloadIcon_Black.png" />
    <Resource Include="Images\downloadIcon_BorderBlack.png" />
    <Resource Include="Images\downloadIcon_Grey.png" />
    <Resource Include="Images\downloadIcon_Orange.png" />
    <Resource Include="Images\downloadIcon_White.png" />
    <Resource Include="Images\errorIcon.png" />
    <Resource Include="Images\eyeIcon.png" />
    <Resource Include="Images\eyeIcon_Blue.png" />
    <Resource Include="Images\folderIcon.png" />
    <Resource Include="Images\inferiorLevelIcon.png" />
    <Resource Include="Images\infoIcon.png" />
    <Resource Include="Images\maximizeIcon.png" />
    <Resource Include="Images\minimizeIcon.png" />
    <Resource Include="Images\moreDetailsIcon_Closed.png" />
    <Resource Include="Images\moreDetailsIcon_Oppened.png" />
    <Resource Include="Images\plusIcon_Black.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\plusIcon_White.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\questionIcon_Black.png" />
    <Resource Include="Images\startIcon_Black.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\startIcon_Blue.png" />
    <Resource Include="Images\startIcon_White.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\stopIcon.png" />
    <Resource Include="Images\successIcon.png" />
    <Resource Include="Images\warningIcon.png" />
  </ItemGroup>

</Project>
